### ISSUE TITLE
Codi inside VirtualEnv 

### ISSUE THREAD

**Issue by Qix-** [metakirby5/codi.vim#46]
OS/X El Capitan, Neovim v0.1.3-350-gc94575f.

Codi inside of a virtual environment seems to be broken. I did a quick search for _virtualenv_ and didn't see anything. Unfortunately this is a bit of a show-stopper for python :/

![codi](https://cloud.githubusercontent.com/assets/885648/19104781/46541248-8a93-11e6-88b8-7332471e78be.gif)

I've even tried doing `pip install neovim` inside of a virtualenv to no avail.

**Comment by metakirby5** [comment]
Can you post the logs? I know what might be wrong, but I can't reproduce the issue.

**Comment by Qix-** [comment]
Here you go - I basically did exactly what is in the gif. From within the virtualenv:

```
[09:13:49.550487] <SNR>116_lo: Darwin/BSD detected, using `script -q /dev/null $bin`
[09:13:49.570127] <SNR>116_user_au[1]: Doing autocommand CodiEnterPre
[09:13:49.622628] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:49.622997] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:49.624445] <SNR>116_user_au[1]: Doing autocommand CodiEnterPost
[09:13:49.645810] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:49.646176] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:49.646439] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:49.646731] <SNR>116_codi_handle_data[9]: async line: >>> >>> >>> 
[09:13:51.942832] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:51.943224] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:51.946522] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:51.950097] <SNR>116_codi_handle_data[9]: async line:  
[09:13:51.958651] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:51.959029] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:51.959296] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:51.959602] <SNR>116_codi_handle_data[9]: async line: >>> ... >>> 
[09:13:52.014298] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:52.014690] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:52.018091] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:52.020038] <SNR>116_codi_handle_data[9]: async line:  =
[09:13:52.031860] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:52.032203] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:52.032486] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:52.033037] <SNR>116_codi_handle_data[9]: async line: >>>   File "<stdin>", line 1
[09:13:52.033318] <SNR>116_codi_handle_data[9]: async line:     =
[09:13:52.033571] <SNR>116_codi_handle_data[9]: async line:     ^
[09:13:52.033869] <SNR>116_codi_handle_data[9]: async line: IndentationError: unexpected indent
[09:13:52.034125] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:52.034281] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:52.059645] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePost
[09:13:52.090119] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:52.090793] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:52.095240] <SNR>116_codi_handle_data[9]: async line:  = 
[09:13:52.106461] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:52.106829] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:52.107105] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:52.107418] <SNR>116_codi_handle_data[9]: async line: >>>   File "<stdin>", line 1
[09:13:52.107670] <SNR>116_codi_handle_data[9]: async line:     = 
[09:13:52.107943] <SNR>116_codi_handle_data[9]: async line:     ^
[09:13:52.108252] <SNR>116_codi_handle_data[9]: async line: IndentationError: unexpected indent
[09:13:52.108531] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:52.108718] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:52.135141] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePost
[09:13:52.195296] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:52.196321] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:52.200841] <SNR>116_codi_handle_data[9]: async line:  = 5
[09:13:52.211970] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:52.212352] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:52.212654] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:52.213003] <SNR>116_codi_handle_data[9]: async line: >>>   File "<stdin>", line 1
[09:13:52.213304] <SNR>116_codi_handle_data[9]: async line:     = 5
[09:13:52.213583] <SNR>116_codi_handle_data[9]: async line:     ^
[09:13:52.214015] <SNR>116_codi_handle_data[9]: async line: IndentationError: unexpected indent
[09:13:52.214380] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:52.214584] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:52.242032] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePost
[09:13:52.563554] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:52.564020] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:52.569341] <SNR>116_codi_handle_data[9]: async line:  = 5
[09:13:52.569726] <SNR>116_codi_handle_data[9]: async line:  
[09:13:52.580879] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:52.581205] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:52.581478] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:52.581799] <SNR>116_codi_handle_data[9]: async line: >>>   File "<stdin>", line 1
[09:13:52.582084] <SNR>116_codi_handle_data[9]: async line:     = 5
[09:13:52.582365] <SNR>116_codi_handle_data[9]: async line:     ^
[09:13:52.582738] <SNR>116_codi_handle_data[9]: async line: IndentationError: unexpected indent
[09:13:52.583020] <SNR>116_codi_handle_data[9]: async line: >>> ... >>> 
[09:13:54.090208] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:54.090932] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:54.093821] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:54.096401] <SNR>116_codi_handle_data[9]: async line:  = 5
[09:13:54.108411] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:54.108738] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:54.109007] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:54.109318] <SNR>116_codi_handle_data[9]: async line: >>>   File "<stdin>", line 1
[09:13:54.109565] <SNR>116_codi_handle_data[9]: async line:     = 5
[09:13:54.109811] <SNR>116_codi_handle_data[9]: async line:     ^
[09:13:54.110060] <SNR>116_codi_handle_data[9]: async line: IndentationError: unexpected indent
[09:13:54.110386] <SNR>116_codi_handle_data[9]: async line: >>> >>> >>> 
[09:13:54.250949] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:54.251441] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:54.254235] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:54.256457] <SNR>116_codi_handle_data[9]: async line:  = 5
[09:13:54.269003] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:54.269393] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:54.269684] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:54.270054] <SNR>116_codi_handle_data[9]: async line: >>>   File "<stdin>", line 1
[09:13:54.270354] <SNR>116_codi_handle_data[9]: async line:     = 5
[09:13:54.270624] <SNR>116_codi_handle_data[9]: async line:     ^
[09:13:54.270901] <SNR>116_codi_handle_data[9]: async line: IndentationError: unexpected indent
[09:13:54.271149] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:54.271311] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:54.298834] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePost
[09:13:54.578047] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:54.578710] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:54.584038] <SNR>116_codi_handle_data[9]: async line:  = 
[09:13:54.595707] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:54.596050] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:54.596331] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:54.596656] <SNR>116_codi_handle_data[9]: async line: >>>   File "<stdin>", line 1
[09:13:54.596917] <SNR>116_codi_handle_data[9]: async line:     = 
[09:13:54.597175] <SNR>116_codi_handle_data[9]: async line:     ^
[09:13:54.597434] <SNR>116_codi_handle_data[9]: async line: IndentationError: unexpected indent
[09:13:54.597711] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:54.597878] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:54.622440] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePost
[09:13:54.747102] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:54.747467] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:54.752443] <SNR>116_codi_handle_data[9]: async line:  =
[09:13:54.764345] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:54.764757] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:54.765105] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:54.765442] <SNR>116_codi_handle_data[9]: async line: >>>   File "<stdin>", line 1
[09:13:54.765690] <SNR>116_codi_handle_data[9]: async line:     =
[09:13:54.765932] <SNR>116_codi_handle_data[9]: async line:     ^
[09:13:54.766180] <SNR>116_codi_handle_data[9]: async line: IndentationError: unexpected indent
[09:13:54.766446] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:54.766620] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:54.794570] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePost
[09:13:54.881826] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:54.882536] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:54.888571] <SNR>116_codi_handle_data[9]: async line:  
[09:13:54.900828] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:54.901235] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:54.901544] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:54.901877] <SNR>116_codi_handle_data[9]: async line: >>> ... >>> 
[09:13:55.016620] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:55.016984] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:55.019653] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:55.033204] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:55.033538] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:55.033821] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:55.034135] <SNR>116_codi_handle_data[9]: async line: >>> >>> >>> 
[09:13:55.296005] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:55.296580] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:55.299868] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:55.302954] <SNR>116_codi_handle_data[9]: async line: a
[09:13:55.317768] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:55.318112] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:55.318447] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:55.319816] <SNR>116_codi_handle_data[9]: async line: >>> Traceback (most recent call last):
[09:13:55.320234] <SNR>116_codi_handle_data[9]: async line:   File "<stdin>", line 1, in <module>
[09:13:55.320603] <SNR>116_codi_handle_data[9]: async line: NameError: name 'a' is not defined
[09:13:55.320917] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:55.321088] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:55.348574] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePost
[09:13:55.367112] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:55.367883] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:55.373010] <SNR>116_codi_handle_data[9]: async line: a 
[09:13:55.387238] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:55.387646] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:55.387985] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:55.388352] <SNR>116_codi_handle_data[9]: async line: >>> Traceback (most recent call last):
[09:13:55.388631] <SNR>116_codi_handle_data[9]: async line:   File "<stdin>", line 1, in <module>
[09:13:55.389071] <SNR>116_codi_handle_data[9]: async line: NameError: name 'a' is not defined
[09:13:55.389408] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:55.389614] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:55.420321] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePost
[09:13:55.533979] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:55.534800] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:55.540077] <SNR>116_codi_handle_data[9]: async line: a = 
[09:13:55.554813] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:55.555305] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:55.555615] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:55.555936] <SNR>116_codi_handle_data[9]: async line: >>>   File "<stdin>", line 1
[09:13:55.556185] <SNR>116_codi_handle_data[9]: async line:     a = 
[09:13:55.556430] <SNR>116_codi_handle_data[9]: async line:        ^
[09:13:55.556739] <SNR>116_codi_handle_data[9]: async line: SyntaxError: invalid syntax
[09:13:55.556996] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:55.557148] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:55.584684] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePost
[09:13:55.672419] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:55.672787] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:55.677076] <SNR>116_codi_handle_data[9]: async line: a = 5
[09:13:55.690523] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:55.690836] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:55.691121] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:55.691649] <SNR>116_codi_handle_data[9]: async line: >>> >>> >>> 
[09:13:56.370556] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:56.370996] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:56.373990] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:56.376330] <SNR>116_codi_handle_data[9]: async line: a = 5
[09:13:56.387258] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:56.387614] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:56.387892] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:56.388213] <SNR>116_codi_handle_data[9]: async line: >>> >>> >>> >>> 
[09:13:57.234125] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:57.234756] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:57.237813] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:57.240113] <SNR>116_codi_handle_data[9]: async line: a = 5
[09:13:57.240480] <SNR>116_codi_handle_data[9]: async line: a
[09:13:57.251469] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:57.251805] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:57.252077] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:57.252447] <SNR>116_codi_handle_data[9]: async line: >>> >>> 5
[09:13:57.252732] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:57.362841] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:57.363320] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:57.366490] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:57.368998] <SNR>116_codi_handle_data[9]: async line: a = 5
[09:13:57.369351] <SNR>116_codi_handle_data[9]: async line: a 
[09:13:57.380108] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:57.380476] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:57.380775] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:57.381112] <SNR>116_codi_handle_data[9]: async line: >>> >>> 5
[09:13:57.381394] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:57.490346] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:57.491091] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:57.492696] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:57.495665] <SNR>116_codi_handle_data[9]: async line: a = 5
[09:13:57.496046] <SNR>116_codi_handle_data[9]: async line: a +
[09:13:57.509203] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:57.509706] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:57.510485] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:57.510852] <SNR>116_codi_handle_data[9]: async line: >>> >>>   File "<stdin>", line 1
[09:13:57.511124] <SNR>116_codi_handle_data[9]: async line:     a +
[09:13:57.511409] <SNR>116_codi_handle_data[9]: async line:       ^
[09:13:57.511675] <SNR>116_codi_handle_data[9]: async line: SyntaxError: invalid syntax
[09:13:57.511931] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:57.595185] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:57.595659] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:57.599072] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:57.601197] <SNR>116_codi_handle_data[9]: async line: a = 5
[09:13:57.601546] <SNR>116_codi_handle_data[9]: async line: a + 
[09:13:57.612212] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:57.612592] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:57.612908] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:57.613256] <SNR>116_codi_handle_data[9]: async line: >>> >>>   File "<stdin>", line 1
[09:13:57.613543] <SNR>116_codi_handle_data[9]: async line:     a + 
[09:13:57.613807] <SNR>116_codi_handle_data[9]: async line:        ^
[09:13:57.614109] <SNR>116_codi_handle_data[9]: async line: SyntaxError: invalid syntax
[09:13:57.614350] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:57.873912] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:57.874387] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:57.877575] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:57.879984] <SNR>116_codi_handle_data[9]: async line: a = 5
[09:13:57.880374] <SNR>116_codi_handle_data[9]: async line: a + 1
[09:13:57.890870] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:57.891247] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:57.891595] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:57.891976] <SNR>116_codi_handle_data[9]: async line: >>> >>> 6
[09:13:57.892229] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:57.970064] <SNR>116_user_au[1]: Doing autocommand CodiUpdatePre
[09:13:57.970588] <SNR>116_codi_do_update[25]: Starting job for buffer 1
[09:13:57.973394] <SNR>116_stop_job_for_buf[8]: Stopping job for buffer 1
[09:13:57.975940] <SNR>116_codi_handle_data[9]: async line: a = 5
[09:13:57.976340] <SNR>116_codi_handle_data[9]: async line: a + 10
[09:13:57.986861] <SNR>116_codi_handle_data[9]: async line: Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[09:13:57.987159] <SNR>116_codi_handle_data[9]: async line: [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
[09:13:57.987425] <SNR>116_codi_handle_data[9]: async line: Type "help", "copyright", "credits" or "license" for more information.
[09:13:57.987730] <SNR>116_codi_handle_data[9]: async line: >>> >>> 15
[09:13:57.987975] <SNR>116_codi_handle_data[9]: async line: >>> >>> 
[09:13:59.961653] <SNR>116_user_au[1]: Doing autocommand CodiLeavePre
[09:13:59.962767] <SNR>116_user_au[1]: Doing autocommand CodiLeavePost
```

**Comment by metakirby5** [comment]
Quite odd that I can't reproduce this. Does this occur when using vim instead of nvim?

**Comment by Qix-** [comment]
Yes - this happens exactly like it does with NeoVim.

Relevant .vimrc:

```viml
call plug#begin('~/.vim/plugged')
Plug 'metakirby5/codi.vim'
call plug#end()

let g:codi#log= '/tmp/codi.log'
```
